### ISSUE TITLE
[LunaChat連携]Discordへの分割送信

### ISSUE THREAD

**Issue by tom1022** [nova-27/DiscordConnect#3]
LunaChatを使用した日本語変換のとき，一度に2回もDiscordに通知されてしまいます

一行にまとめることはできないのでしょうか

**Comment by nova-27** [comment]
はじめまして

`toDiscordFormat`を`""`にして、`japanizeFormat`で`{original}`を利用することで実現可能です。

例:
```yml
toDiscordFormat: ""
japanizeFormat: "*({server})* **{sender}** : {original} ({japanized})"
```

![image](https://user-images.githubusercontent.com/33594303/147409312-f333afe8-d639-4ecf-bbc9-0afb214558ea.png)

**Comment by tom1022** [comment]
返信ありがとうございます

例を下のように編集して見ました
```
token: token
chatChannelIDs:
- channnelID
playingGameName: サーバー稼働中！（{players}/{max}人）

prefix: "!"
toMinecraftFormat: "[{name}@§9Discord§r] : "
#toDiscordFormat: "**[{sender}@{server}]** : {message}"
toDiscordFormat: ""
updateCheck: true

# LunaChat使用時にのみ有効 (Only when using the LunaChat plugin)
japanizeFormat: "**[{sender}@{server}]** : {original} ({japanized})"
#japanizeFormat: "*({server})* **{sender}** __JP__: {japanized}"

# この値は変更しないでください！ (Don't change the value!)
configVersion: 3
```

ですがコンソールでは英字で"test"，日本語で"テスト"と送信されていますが二枚目の画像でのDiscord上では前者しか送信されていません
![image](https://user-images.githubusercontent.com/42195304/147427208-22f81e71-c8fa-46e5-9db7-d88e346fb9ba.png)
![image](https://user-images.githubusercontent.com/42195304/147427501-d98698b6-0728-47d4-8591-2e5ed8658f4a.png)

日本語で送信してくる人もいるのでどちらにも対応できるようにすることができません
どのようにconfigを編集すればよろしいのでしょうか

**Comment by tom1022** [comment]
バグだったんですね．
いつ頃，修正されたバージョンはリリースしそうですか？

**Comment by nova-27** [comment]
他のバグも修正してからリリースするため、数日は掛かりそうです

**Comment by nova-27** [comment]
続きは #4 で扱います
