### ISSUE TITLE
[LunaChat連携]japanize化されないとき、discordに転送されない

### ISSUE THREAD

**Issue by nova-27** [nova-27/DiscordConnect#4]
返信ありがとうございます

例を下のように編集して見ました
```
token: token
chatChannelIDs:
- channnelID
playingGameName: サーバー稼働中！（{players}/{max}人）

prefix: "!"
toMinecraftFormat: "[{name}@§9Discord§r] : "
#toDiscordFormat: "**[{sender}@{server}]** : {message}"
toDiscordFormat: ""
updateCheck: true

# LunaChat使用時にのみ有効 (Only when using the LunaChat plugin)
japanizeFormat: "**[{sender}@{server}]** : {original} ({japanized})"
#japanizeFormat: "*({server})* **{sender}** __JP__: {japanized}"

# この値は変更しないでください！ (Don't change the value!)
configVersion: 3
```

ですがコンソールでは英字で"test"，日本語で"テスト"と送信されていますが二枚目の画像でのDiscord上では前者しか送信されていません
![image](https://user-images.githubusercontent.com/42195304/147427208-22f81e71-c8fa-46e5-9db7-d88e346fb9ba.png)
![image](https://user-images.githubusercontent.com/42195304/147427501-d98698b6-0728-47d4-8591-2e5ed8658f4a.png)

日本語で送信してくる人もいるのでどちらにも対応できるようにすることができません
どのようにconfigを編集すればよろしいのでしょうか

_Originally posted by @tom1022 in https://github.com/nova-27/DiscordConnect/issues/3#issuecomment-1001293485_

**Comment by nova-27** [comment]
@tom1022

このPre-releaseで問題が解決するかどうか試していただけますか？
https://github.com/nova-27/DiscordConnect/releases/tag/v2.4

**Comment by tom1022** [comment]
テストしてみたところ，この様になりました．
![image](https://user-images.githubusercontent.com/42195304/147760910-5b5adb9a-2cdd-4b08-9262-fb4d90915724.png)
![image](https://user-images.githubusercontent.com/42195304/147761706-974d22b1-ce6c-4ad5-8a52-1db587177738.png)
![image](https://user-images.githubusercontent.com/42195304/147761300-1e557fac-bcaa-4401-b30b-471ad4341fe5.png)
見たところ`toDiscordFormat`が機能せず，`japanizeFormat`のみが機能しているためもともとの日本語文がもう一度日本語変換せれているようです．

また，Discord上で貼った写真のURLがMinecraft上でURLとして表示されていました．

Javaが全くわからないで申し訳ありませんが，デバッグ頑張ってください．

**Comment by nova-27** [comment]
確認ありがとうございます
修正しましたので、お手数ですがもう一度ご確認お願いします

ファイルは`DiscordConnect-2.4-pre2.jar`です
https://github.com/nova-27/DiscordConnect/releases/tag/v2.4

**Comment by tom1022** [comment]
修正ありがとうございます．

確認してみたところ問題なさそうです．
何かまたバグがあれば，Issuesで新しく会話を作成したいと思います．

ありがとうございました．
